services:
  jetstream:
    image: ghcr.io/ericvolp12/jetstream:main
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: jetstream
    network_mode: host
    volumes:
      - ./data:/data
    environment:
      - JETSTREAM_DATA_DIR=/data
