services:
  jetstream:
    image: ghcr.io/bluesky-social/jetstream:${JETSTREAM_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: jetstream
    network_mode: host
    volumes:
      - ./data:/data
    environment:
      - JETSTREAM_DATA_DIR=/data
      - JETSTREAM_ZSTD_DICTIONARY_PATH=/zstd-dictionary
      - JETSTREAM_MAX_SUB_RATE=1_000_000
